#KERSLAM: Keyword Extraction and Recognition with Sentence Level Association Maps

import getKeywords #to use the getKeywords function
"""
main()

contains 3 demos of the getKeywords function
"""
def main():
  print(getKeywords.getKeywords("Graham’s number is a whole number, but it’s so ridiculously large that you can’t even comprehend its value. If you tried to write down Graham’s number, you could not, because the number of digits in it, say there are a of them, is so large that there’s not enough space in the observable universe to write down them all. Even if each digit took up a Planck-volume sized region of space (a Planck volume is orders of magnitude smaller than a proton, and that’s an understatement), there would still be too many digits to be contained in the observable universe. In fact, even a, which is the number of digits in Graham’s number, is itself so large that you could not write it down, because the number of its digits, say there are b of them, is so large that there aren’t enough Planck volumes in the observable universe to contain them all. In fact, even b is a number so large that you could not write out its digits (say there are c of them). This process continues for a number of times so large that even the number of times this process repeats exceeds the number of Planck volumes in the observable universe. This blew my mind when I learned it, so just sharing it any fellow math nerds out there. (If you’re having trouble imagining this, suppose some really large number N has a million digits (let a be 1,000,000). Then in a very small universe containing fewer than a million Planck volumes, you could not write down N because it has too many digits. But, you could write down a itself (which is 1,000,000), because it only has 7 digits (let b be 7, and since b has one digit, let c be 1). Well, Graham’s number is so large that this sequence of variables a, b, c, d, …, is too large to even fit in the universe"))
  print(getKeywords.getKeywords("The locavore movement will benefit local environments but on a larger scale, it will harm the greater environment. Locavores argue that eating regional produce will reduce the carbon footprint created during food transportation. For instance, an article written by Jennifer Maiser identifies that “a March 2005 study by the journal Food Policy [...] found that the miles that organic food travels to our plate creates environmental damage” (Source A). However, this only analyses a singular impact of buying local. There are other factors that can also impact how much our food contributes to pollution. A statistical breakdown of pollution in all stages of food production found in Conservation Magazine shows that transport is only a small fraction of a product’s carbon footprint, dwarfed by the carbon emitted during production (Source D). Therefore, it’s entirely possible for consumers to pick a more polluting food product by buying locally if the local product was grown less sustainably. Yet this is more than a possibility, this is a reality. For instance, an article written by James McWilliams for Forbes notes that a study has shown that importing lamb to Britain from New Zealand is actually greener than buying local lamb in Britain. McWilliams explains this finding, noting “New Zealand lamb is raised on pastures with a small carbon footprint, whearas most english lamb is raised in a factory-like conditions with a big carbon footprint” (Source C). Therefore, the narrow view purported by locavores of sustainability can actually counter sustainability at large."))
  print(getKeywords.getKeywords("From Heian Japan to medieval France, the differences between men and women have dominated literary discourse. With a binary opposition being defined as a pair of related concepts with antipodal meanings, it is easy to see how classical discourse has centered around the idea that the two genders exist as opposites, each serving as the antithesis of its counterpart. After all, pitting the genders against each other undeniably allows for a more unambiguous division of societal groups and—historically—has facilitated an unmistakably unequal distribution of power. Sei Shōnagon, in her novel The Pillow Book, decides to embrace this binary perception of gender, highlighting the differing natures of men and women and using these to determine the behaviors appropriate for a member of each group. Viewing the issue from a different perspective, Christine de Pizan issues a harsh rebuke of all attempts to utilize gender as a discriminant when ascertaining social utility, and her efforts serve to blur established divisions of gender and redefine what it means to be masculine or feminine. In The Pillow Book, Sei Shōnagon assigns behavior codes to men and women in order to affirm the binary opposition of the two genders and advocate for a gender-specific method of conduct centered around male chivalry and female refinement; this is in stark contrast to The Book of the City of Ladies, in which Christine de Pizan challenges the binary nature of gender—through allusions to mythological and historical female figures—in an effort to contradict the notion that men and women occupy the predetermined social roles of scholarly husband and subservient wife."))
  print("got keywords!")


main()
